### ISSUE TITLE
FFMPEG video processing error

### ISSUE THREAD

**Issue by cl3m3nt** [surfriderfoundationeurope/mot#45]
Dear mot developer, 

I got unexpected error when processing video that could be related to ffmpeg package.
When calling the AI service, some video looks to be processed ok by the AI, however the response back from the request call never make it.
After a while, the following log has been observed from the AI:

/usr/local/lib/python3.6/dist-packages/werkzeug/filesystem.py:60: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'
  BrokenFilesystemWarning,
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 297, in execute
    write(data)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 278, in write
    self.wfile.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
TimeoutError: [Errno 110] Connection timed out

162.142.125.40 - - [29/Apr/2021 08:43:35] code 400, message Bad request syntax ('\x16\x03\x01\x00{\x01\x00\x00w\x03\x03 Rn8\x1fa\x93o" mI\xe3t\t\xbe\xbf\xe4\xf9\x06 \x850J\xac\x05\xe5\x05\xcc_\x08\xce\x00\x00\x1a\xc0/\xc0+\xc0\x11\xc0\x07\xc0\x13\xc0\t\xc0\x14\xc0')
162.142.125.40 - - [29/Apr/2021 08:43:35] "{w Rn8a\x93o" mI\xe3t	\xbe\xbf\xe4\xf9 \x850J\xac\xe5\xcc\xce\xc0/\xc0+\xc0\xc0\xc0\xc0	\xc0\xc0" HTTPStatus.BAD_REQUEST -

During the processing of the video by the AI, the following (new) message appeared, which might indicate a root cause from ffmpeg:

[swscaler @ 0x555ecf78f640] deprecated pixel format used, make sure you did set range correctly

I appreciate your help.

Kind regards

**Comment by cl3m3nt** [comment]
This video is processed correctly: https://storage.googleapis.com/plasticorigin/6250052d-f716-435c-9d71-83ad49347c5e.mp4
This video is NOT processed correctly and raised previously described: 
https://storage.googleapis.com/plasticorigin/bf1a60f8-ad7a-4572-ac9c-bf7ff042a301.mp4

**Comment by cl3m3nt** [comment]
After checking, the message:
[swscaler @ 0x55b60ff6d900] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to 'tmp/tmp_6250052d-f716-435c-9d71-83ad49347c5e.mp4_split/frame_%4d.jpeg':
is also present for working video. 
Hence not sure this necessarily come from ffmpeg
